version: '3.5'


services:

  api:
    build: ./src
    restart: on-failure
    environment:
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - PROJECT_NAME=${PROJECT_NAME:-ugc}
      - RSA_PUBLIC_PATH=/run/secrets/rsa_public
      - SENTRY_DSN=${SENTRY_DSN}
      - LOGSTASH_HOST=${LOGSTASH_HOST:-logstash}
      - LOGSTASH_PORT=${LOGSTASH_PORT:-5000}
    secrets:
      - rsa_public
    expose:
      - 8000

  nginx:
    image: nginx:stable
    container_name: ugc-nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
  
  mongo:
    image: mongo
    command: mongod --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tmp/mongo_/data:/data/db

  logstash:
    image: logstash:8.10.2
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5000/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

secrets:
  rsa_public:
    file: ./keys/rsa.pub

volumes:
  esdata: